### PR TITLE
🎉 Mb add dev team info

### PR DESCRIPTION
**Pull request by migbro**
Added cwl style guide and a dev team life cycle overview

### CODE REVIEW

**Comment by migbro** [comment]
This also includes updates from Yuankun's `yuankun/bixu-updates` branch as I wanted to build off of that one as it was most relevant to our team

**Comment by dankolbman** [comment]
The CWL commit looks pretty stand alone from the other PR. Can you rebase it as-is? We can merge the bix stuff independently.
Could you also add an emoji to the PR title?

**Comment by migbro** [comment]
> The CWL commit looks pretty stand alone from the other PR. Can you rebase it as-is? We can merge the bix stuff independently.
> Could you also add an emoji to the PR title?

Def can add an emoji....rebase as-is? Meaning, go back master and add only the changes I made for cwl, then in a different PR, pull in Yuankun's pull my additions to his?

**Comment by migbro** [comment]
Also, I guess the colon-phrase-colon nomenclature doesn't work on PR titles...do I need to enable/install an emoji keyboard?

**Comment by dankolbman** [comment]
Yuankun's changes are in #19 so they'll get merged there so you can remove all of his commits from this PR. That way only your changes are evaluated in reviewing this pull request.

Yeah, it's annoying that Gtihub doesn't interpret the colon emoji names yet, but you can replace it using the emoji keyboard (ctrl+command+space)

**Comment by migbro** [comment]
Given the number of commits to drop, I will push a new branch instead and delete this one

**Pull request closed without merging**
